const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Lacoste Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 80,
      countInStock: 20,
      brand: "Lacoste",
      rating: 4.7,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 30,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 125,
      countInStock: 12,
      brand: "Puma",
      rating: 4.5,
      numReviews: 7,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Slim Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 140,
      countInStock: 17,
      brand: "Adidas",
      rating: 5.0,
      numReviews: 7,
      description: "high quality product",
    },
  ],
};

export default data;
